name: SlackIntegration
main: com.teej107.slack.Slack
version: ${project.version}
softdepend: [GriefPrevention]

commands:
  slack:
    default: op
    permission: slack.use
    usage: |
      /slack url [url]
      /slack port [port]
      /slack token [token]
      /slack add <channel>
      /slack remove <channel>
      /slack channels
      /slack reload
      /slack format [format]
      /slack deaths [true|false]
      /slack achievements [true|false]